[RCT-90] What's New in React
arvin-viar/dotTheory-React pull request #7
Opened 2022-10-19 11:26 UTC by arvin-viar

# Related Tickets

https://codeandtheory.atlassian.net/browse/RCT-90

# Description

Please merge after PR #6 

This PR implements the new features in react 16, 17 and 18.

# Validation

https://user-images.githubusercontent.com/77320674/196678076-0a091b72-2fd2-4d91-befd-82865a84281f.mov

# Risks

2023-01-30 12:46 UTC, lycoangelo approved these changes

2023-01-30 12:46 UTC, lycoangelo commented on src/components/RouterCourse/Courses/CourseContainer.js
> +}
This can be rewritten into an implicit return.

2023-01-30 12:46 UTC, lycoangelo commented on src/components/RouterCourse/Courses/index.js
> +);
We can implement a component object mapping here.

2023-01-30 12:46 UTC, lycoangelo commented on src/components/RouterCourse/Teachers/index.js
> +  );
We can also rewrite this one and implement implicit return.

2023-01-30 12:46 UTC, lycoangelo commented on src/components/WhatsNew/ErrorBoundaries/index.js
> +}
We can also rewrite this one and implement implicit return.

2023-01-30 12:46 UTC, lycoangelo commented on src/pages/RouterCourse/index.js
> +        )}
We can also implement a component object mapping here.

2023-01-30 12:46 UTC, lycoangelo commented on src/pages/WhatsNew/index.js
> +      </div>
We can also implement a component object mapping here.

2023-01-30 12:46 UTC, lycoangelo commented on src/components/WhatsNew/Portals/portal.scss
> +}
We can remove this file.

2023-01-30 12:46 UTC, lycoangelo commented on src/pages/App/App.js
> +}
This can also be an implicit return.

2023-01-30 12:48 UTC, lycoangelo requested changes
Hi @arvin-viar, I wrote some minor request changes.

2023-02-01 09:31 UTC, arvin-viar commented on src/components/RouterCourse/Teachers/index.js
> +  );
updated, implemented implicit return

2023-02-01 09:31 UTC, arvin-viar commented on src/components/RouterCourse/Courses/index.js
> +);
updated, implemented component object mapping

2023-02-01 09:31 UTC, arvin-viar commented on src/components/RouterCourse/Courses/CourseContainer.js
> +}
updated, applied implicit return

2023-02-01 09:37 UTC, arvin-viar commented on src/components/WhatsNew/ErrorBoundaries/index.js
> +}
updated, applied implicit return

2023-02-01 09:39 UTC, arvin-viar commented on src/pages/RouterCourse/index.js
> +        )}
updated, applied component object mapping

2023-02-01 09:39 UTC, arvin-viar commented on src/pages/WhatsNew/index.js
> +      </div>
updated, applied component object mapping

2023-02-01 09:39 UTC, arvin-viar commented on src/components/WhatsNew/Portals/portal.scss
> +}
updated, file removed

2023-02-01 09:40 UTC, arvin-viar commented on src/pages/App/App.js
> +}
updated, applied implicit return

2023-02-01 15:36 UTC, lycoangelo approved these changes

2023-02-01 15:36 UTC, merged